### ISSUE TITLE
Categorical instance to return value rather than index?

### ISSUE THREAD

**Issue by baskaransri** [jtobin/mwc-probability#18]
I'd quite like if there was an analogue of categorical like:
```haskell
discrete :: (Foldable f, PrimMonad m) => f (Double, a) -> Prob m a
```
which would sample from the container, choosing each `a` with the associated probability.

**Comment by jtobin** [comment]
I have an unequal probability sampling implementation in a slightly less well-known library called [sampling](https://github.com/jtobin/sampling) (see `psample`, `presample`), but I agree an implementation would be nice here too.  I'll add it.
