### ISSUE TITLE
compile failures with base < 4.8

### ISSUE THREAD

**Issue by hvr** [jtobin/mwc-probability#4]
The `.cabal` files specifies compatibility with `base >= 4`, however, when compiling with `base-4.7` or older, build failures as below occur.

I've already revised the meta-data for the affected releases:

- https://hackage.haskell.org/package/mwc-probability-1.3.0/revisions/
- https://hackage.haskell.org/package/mwc-probability-1.2.2/revisions/
- https://hackage.haskell.org/package/mwc-probability-1.2.1/revisions/
- https://hackage.haskell.org/package/mwc-probability-1.2.0/revisions/

So there's no immediate action needed. For the next release of `mwc-probability` it would be great if it either restores compatibility with `base < 4.8`, or comes with a lower bound `base >= 4.8`.
If you want to test your package against all versions of `base` announced in the .cabal file, you can e.g. use https://github.com/hvr/multi-ghc-travis.

See also https://matrix.hackage.haskell.org/package/mwc-probability

If you have any questions, please feel free to ask me!

```
Configuring library for mwc-probability-1.3.0..
Preprocessing library for mwc-probability-1.3.0..
Building library for mwc-probability-1.3.0..
[1 of 1] Compiling System.Random.MWC.Probability ( src/System/Random/MWC/Probability.hs, /tmp/matrix-worker/1499583492/dist-newstyle/build/x86_64-linux/ghc-7.8.4/mwc-probability-1.3.0/build/System/Random/MWC/Probability.o )

src/System/Random/MWC/Probability.hs:222:7:
    Not in scope: type constructor or class ‘Traversable’

src/System/Random/MWC/Probability.hs:224:9:
    Not in scope: ‘traverse’
    Perhaps you meant one of these:
      ‘F.traverse_’ (imported from Data.Foldable),
      ‘reverse’ (imported from Prelude)

src/System/Random/MWC/Probability.hs:262:7:
    Not in scope: type constructor or class ‘Traversable’

src/System/Random/MWC/Probability.hs:263:18:
    Not in scope: ‘traverse’
    Perhaps you meant one of these:
      ‘F.traverse_’ (imported from Data.Foldable),
      ‘reverse’ (imported from Prelude)

```

**Comment by jtobin** [comment]
Hey, thanks much!  Will be fixed in the next release. :smile:
